def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_static_view('deform_static', 'deform:static')
    config.add_route('home', '/')
    config.add_route('login', '/login/')
    config.add_route('logout', '/logout/')
    config.add_route('recover', '/recover/')
    config.add_route('signin', '/signin/')
    config.add_route('signup', '/signup/')
    config.add_route('schedule', '/schedule/')
    config.add_route('edit_meeting', '/settings/')
    config.add_route('session', '/session/{session_id:\d+}/')
    config.add_route('edit_session', '/session/{session_id:\d+}/edit/')
    config.add_route('activity', '/activity/{activity_id:\d+}/')
    config.add_route('edit_activity', '/activity/{activity_id:\d+}/edit/')
    config.add_route('settings', 'profile/settings/')
    config.add_route('profile_list', 'profile/')
    config.add_route('profile', 'profile/{uid}/')
    config.add_route('success_signin', '/signup/success/')
    config.add_route('failure', '/failure/*action')
    config.add_route('captcha', '/captcha/{captcha_id}.png')
    config.add_route('admin_roles', '/admin/roles/')
    config.add_route('mumble_join', '/join/*channel', factory='pyramid_mumble.resources.mumble.MumbleSessionFactory')
    config.add_route('mumble_leave', '/leave/', factory='pyramid_mumble.resources.mumble.MumbleSessionFactory')
